/*-
 * GNU GENERAL PUBLIC LICENSE, version 3
 * See LICENSE file for detail.
 *
 * Author: Yulong Yu
 * Copyright(c) 2015-2026 Yulong Yu. All rights reserved.
 */

/*! \file finUiFigureWidget.h
 *  \brief Declaration of the widget that hosts figure rendering.
 *
 *  finUiFigureWidget owns the figure container that stores the current drawing result and the graph-panel
 *  helper responsible for painting that container onto the widget surface.
 */

#ifndef FINUIFIGUREWIDGET_H
#define FINUIFIGUREWIDGET_H

#include <QWidget>

#include "finErrorCode.h"
#include "finFigureContainer.h"
#include "finGraphPanelWidget.h"


/*! \class finUiFigureWidget
 *  \brief QWidget wrapper that stores and renders a FIN figure.
 *
 *  The widget keeps a finFigureContainer instance as its backing data model and a finGraphPanelWidget as
 *  the rendering helper. Call applyFigure() after updating the container so the widget size and graph panel
 *  are synchronized with the current graph configuration before the next paint event.
 */
class finUiFigureWidget : public QWidget
{
protected:
    finFigureContainer _figcontainer;  //!< Figure data currently owned and displayed by this widget.
    finGraphPanelWidget _graphpanel;   //!< Rendering helper bound to this widget.

public:
    /*!
     *  \brief Constructs an empty figure widget.
     *
     *  The internal graph panel is bound to this widget during construction so later paint events can be
     *  forwarded directly to it.
     *
     *  \param parent  Parent widget, or \c nullptr to create a top-level widget.
     *  \param f       Window flags passed to QWidget.
     */
    finUiFigureWidget(QWidget *parent = Q_NULLPTR, Qt::WindowFlags f = Qt::WindowFlags());

    /*!
     *  \brief Returns the current figure container as a read-only pointer.
     */
    const finFigureContainer *getFigureContainer() const;

    /*!
     *  \brief Returns the current figure container as a mutable pointer.
     */
    finFigureContainer *getFigureContainer();

    /*!
     *  \brief Returns the graph-panel helper as a read-only pointer.
     */
    const finGraphPanelWidget *getGraphPanel() const;

    /*!
     *  \brief Returns the graph-panel helper as a mutable pointer.
     */
    finGraphPanelWidget *getGraphPanel();

    /*!
     *  \brief Applies the current figure configuration to the widget.
     *
     *  This resizes the widget to the panel size stored in the figure container's graph configuration,
     *  binds the container to the graph panel, and triggers a repaint.
     *
     *  \return \c finErrorKits::EC_SUCCESS after the widget and graph panel have been updated.
     */
    finErrorCode applyFigure();

protected:
    /*!
     *  \brief Paint-event handler that delegates drawing to the graph panel.
     *
     *  \param e  The paint event generated by Qt.
     */
    virtual void paintEvent(QPaintEvent *e);
};

#endif // FINUIFIGUREWIDGET_H
